/** Option sets shared by lead forms and schemas. Kept free of Zod so UI code can import it cheaply. */
export const leadOptions = {
  cctvProperty: ['Home', 'Shop', 'Office', 'School', 'Hospital', 'Warehouse', 'Factory'] as const,
  cctvCameras: ['1 – 4', '5 – 8', '9 – 16', '17 – 32', 'More than 32', 'Not sure yet'] as const,
  solarBill: [
    'Below ₹2,000',
    '₹2,000 – ₹5,000',
    '₹5,000 – ₹10,000',
    '₹10,000 – ₹25,000',
    '₹25,000 – ₹50,000',
    'Above ₹50,000',
  ] as const,
  solarProperty: [
    'Home',
    'Housing Society',
    'Shop / Showroom',
    'Office',
    'School / Institution',
    'Hospital',
    'Factory / Warehouse',
    'Farm / Agriculture',
  ] as const,
  solarIntent: ['calculate', 'consultation'] as const,
  generalService: [
    'Pawan Putra Secure (CCTV & Security)',
    'Pawan Putra Connect (Networking & IT)',
    'Pawan Putra Solar',
    'Pawan Putra Digital',
    'Pawan Putra Space (Real Estate & Construction)',
    'Multiple / Not sure yet',
  ] as const,
  digitalService: [
    'Website Development',
    'Mobile App Development',
    'Software Development',
    'ERP',
    'CRM',
    'SEO',
    'Google Ads',
    'Meta Ads',
    'Social Media Marketing',
    'Branding',
    'Graphic Designing',
    'Not sure yet',
  ] as const,
  connectProperty: ['Home', 'Office', 'School / College', 'Hospital', 'Hotel', 'Factory / Warehouse', 'Shop / Showroom', 'Other'] as const,
  connectService: ['Fiber Networking', 'LAN / CAN', 'Wi-Fi', 'Routers', 'Switches', 'Server Racks', 'IT Support', 'Not sure yet'] as const,
  spaceService: ['Real Estate', 'Architecture', 'Interior Design', 'Construction', 'Property Solutions', 'Renovation'] as const,
  spaceProperty: ['Plot / Land', 'Flat / Apartment', 'Villa / Independent House', 'Commercial Space', 'Other'] as const,
};
